[project]
name = "quick-audio-cloner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.16"
dependencies = [
    "pydub>=0.25.1",
    "python-dotenv>=1.0.1",
    "tts>=0.22.0",
    "yt-dlp>=2025.1.26",
]
